language: python
python: 
    - "2.7"
    - "3.4"
env:
    - DJANGO="Django>=1.6.0,<1.7.0"
    - DJANGO="Django>=1.7.0,<1.8.0"
    - DJANGO="Django>=1.8.0,<1.9.0"
    - DJANGO="Django>=1.9.0,<1.10.0"

install:
    - pip install -q $DJANGO
    - pip install -r requirements.txt

script:
    - cd project
    - python manage.py syncdb --noinput
    - python manage.py migrate --noinput || true # Only for 1.7/1.8
    - python manage.py test --noinput
    - cd -
